### ISSUE TITLE
Wrong link to deployed app in README?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI532_Group17-R#17]
Hi @GuanshuTao @mmyz88 @yuanxiongbear @MarcSunUBC ! I looks like the link in your readme is to the Python dashboard, is that correct? If so, could you please update with the R deployed link instead?

**Comment by mmyz88** [comment]
Hey @joelostblom thanks for heads up!! Yea this was a mistake when I added the demo GIFs for both repos last night. It is fixed now.

This was after our v3.0 release though, so the release submitted should be correct (although didn't have the gif).

**Comment by joelostblom** [comment]
Thanks for the quick fix!
